### ISSUE TITLE
Library not supported

### ISSUE THREAD

**Issue by igorkietrz** [3arthur6/BluetoothLibraryPatcher#1]
Here  is file

[BluetoothLibPatcher-files - MediaFire](https://www.mediafire.com/file/hqj4dbe0esu7c7j/BluetoothLibPatcher-files.tar/file) 
My Phone is Galaxy A71 - Android 11

**Comment by 3arthur6** [comment]
Hey
Does latest updates fixed it?

**Comment by igorkietrz** [comment]
Nvm, I realised that I'm using custom kernel that probaly had it patched
