### ISSUE TITLE
Samsung Galaxy Note 20 Ultra - Unsupported Library 

### ISSUE THREAD

**Issue by TheBrokenG0d** [3arthur6/BluetoothLibraryPatcher#10]
Wanted to put it out here that the newest update doesn't work for me. I'm just running a rooted stock rom and the previous version worked. 
[BluetoothLibPatcher-files.tar.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9295039/BluetoothLibPatcher-files.tar.zip)

I had to add .zip to the tar file to get it to upload.

**Comment by 3arthur6** [comment]
Sorry it have been fixed. Install it again.
