### ISSUE TITLE
My device's Bluetooth Library isn't supported

### ISSUE THREAD

**Issue by chillrage** [3arthur6/BluetoothLibraryPatcher#11]
device - Galaxy M30s running on PrishOS v7 (A50s OneUI 3 port)
the issue is caused while trying to update to 2.4.2 from 2.4.1 #6

**Comment by 3arthur6** [comment]
Hey
Ported roms have always been difficult to handel..
Please try again and upload the tar file if it fails again.

**Comment by chillrage** [comment]
sorry about the late reply, the module works perfectly fine now
you can close the issue, thanks!
