### ISSUE TITLE
SM-G973F

### ISSUE THREAD

**Issue by aliafshany** [3arthur6/BluetoothLibraryPatcher#13]
hello there 
i tried to flash the module via Magisk, but it failed and led me here.

this is my logs.
please investigate this
my phone specs:
android 12 + root (for sure) + stock rom

[BluetoothLibPatcher-files.tar.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9318030/BluetoothLibPatcher-files.tar.zip)
.

**Comment by 3arthur6** [comment]
Hey
Humm not sure what happened.
Try again or download the latest release [here](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/download/v2.4.2/BluetoothLibraryPatcher_magisk_2.4.2.zip) and install it in magisk from local storage.

**Comment by aliafshany** [comment]
i installed the latest version, and it's working
initially, i flashed it from "Fox's Mmm", maybe there was an old version of it.

btw thank you
