### ISSUE TITLE
The module.prop file appears as version 2.4.2 and magisk asks to redownload and reinstall 

### ISSUE THREAD

**Issue by ZeroDev99** [3arthur6/BluetoothLibraryPatcher#17]
![Screenshot_20220818-095103_One UI Home](https://user-images.githubusercontent.com/98488108/185439562-01910c05-bf65-4a55-b316-0808418d89c6.png)

**Comment by TheSingular** [comment]
For now, after updating and rebooting if you haven't done so yet, you can go to /data/adb/modules/BluetoothLibraryPatcher and edit lines "version=v2.4.2" to "version=v2.4.3" and "versionCode=242" to "versionCode=243" in module.prop file there as a workaround.

**Comment by ZeroDev99** [comment]
Okay, I will try it

**Comment by 3arthur6** [comment]
Sorry I just fixed it.
Thanks
