### ISSUE TITLE
Bluetooth library not supported

### ISSUE THREAD

**Issue by dtriguero** [3arthur6/BluetoothLibraryPatcher#18]
[BluetoothLibPatcher-files.tar.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9386048/BluetoothLibPatcher-files.tar.zip)

**Comment by 3arthur6** [comment]
Not sure what happened and where you get the module.
Go to latest 2.4.3 version.
You should always download it from github or from magisk manager.
