### ISSUE TITLE
Does not save pairings 

### ISSUE THREAD

**Issue by ZeroDev99** [3arthur6/BluetoothLibraryPatcher#19]
Just updated to 2.4.4 and it's not saving matchups after reboot
[Bluetooth library](https://www.mediafire.com/file/j4rs773usj5iquy/BluetoothLibPatcher-files.tar/file)

**Comment by 3arthur6** [comment]
Hey
Sorry I pushed again the update.
Try to install it again it should be ok.

**Comment by Meowxhehe** [comment]
I'm having issues pairing my watch 4 again after installing and running the commands in termux.
Wear still wants me to reset my watch..

**Comment by ZeroDev99** [comment]
Ok, I'm going to try

**Comment by ZeroDev99** [comment]
> Hey Sorry I pushed again the update. Try to install it again it should be ok.

I'm here, thanks
