### ISSUE TITLE
Unable to install from twrp: ERROR CODE 2

### ISSUE THREAD

**Issue by DJLeleX** [3arthur6/BluetoothLibraryPatcher#21]
Unable to install v2.4.4 from twrp. Already installed v2.4.3 from twrp.
XDA forums are offline now, that's why I'm posting here.
Device is Galaxy S10+ (SM-G975F) on A11.
v2.4.3 is working fine with my galaxy watch 5 pro.
Screenshot attached below.

![Screenshot_2022-09-02-07-04-08](https://user-images.githubusercontent.com/29524391/188063142-bc3e8e1c-1c2e-4767-805f-610e20b5b445.png)

**Comment by 3arthur6** [comment]
Hey
Just fixed it with v2.5
