### ISSUE TITLE
Fold 4 support

### ISSUE THREAD

**Issue by hogyoku** [3arthur6/BluetoothLibraryPatcher#22]
https://drive.google.com/file/d/185hEuXequaoYT_y6Hh2rRHMjvzR_FW4k/view?usp=drivesdk

**Comment by 3arthur6** [comment]
Hey
Just fixed it with v2.5

**Comment by Conan179** [comment]
i can't install it on my fold 4, there is only a twrp package, but there is no twrp for the fold4 yet, i need the magisk module.

**Comment by 3arthur6** [comment]
> i can't install it on my fold 4, there is only a twrp package, but there is no twrp for the fold4 yet, i need the magisk module.

Sorry for the upload issue. The file should be here now.

**Comment by Conan179** [comment]
Thanks :) Installation went without any problems, I'll see tonight if I can pair my Samsung watches.
