### ISSUE TITLE
Slow script execution during boot on Galaxy Note 9 running Android 10

### ISSUE THREAD

**Issue by brusyev** [3arthur6/BluetoothLibraryPatcher#23]
It appears that during boot the latest version of BluetoothLibraryPatcher is running the module script noticeably slower on Galaxy Note 9 (Android 10) and latest version of TWRP Crownlite. Not sure if this is TWRP related or something else is causing it to run slower.

**Comment by brusyev** [comment]
This would be the latest version of magisk module. Upon the reboot it takes a few minutes for the script to kick in to temporarily disable bluetooth, enable airplane mode.

**Comment by 3arthur6** [comment]
What you say is not clear.
What is wrong? The patch works right so?

**Comment by brusyev** [comment]
The patch works great. When the phone is restarted it looks like the patch runs a script which temporarily disabled bluetooth and then enables it again. This process started taking longer for some reason. Otherwise the patch works great. Thank you for all the work on this.

**Comment by 3arthur6** [comment]
Humm no this clearly doesn't disable nor enable bluetooth at any moments.
Not sure what is your issue but it's not related to this.
