### ISSUE TITLE
Paring my samsung watch are stays at "Kopplung wird abgeschlossen..."

### ISSUE THREAD

**Issue by Conan179** [3arthur6/BluetoothLibraryPatcher#24]
Hi first. I installed the v2.5 on my Galaxy Fold4, but I can't pair my two Samsung watches (gear s2 and watch3), the message remains: "Pairing is being completed...", can you help me with that does the pairing work?

**Comment by Conan179** [comment]
It's the same error as the https://github.com/3arthur6/BluetoothLibraryPatcher/issues/5
There is no twrp for the fold 4 yet.

**Comment by Conan179** [comment]
https://www.dropbox.com/s/hsby8bc3f97xlov/bluetoothlibpatcher-files.tar?dl=0
Fold4

**Comment by 3arthur6** [comment]
It seems fixed according to you.

**Comment by Conan179** [comment]
error is back with a13
