### ISSUE TITLE
Phone not booting anymore

### ISSUE THREAD

**Issue by arminask** [3arthur6/BluetoothLibraryPatcher#26]
Flashed using TWRP, now my phone doesn't boot anymore.
![image](https://user-images.githubusercontent.com/72100724/200366212-8c040158-896a-4de9-954c-f9ee0896558c.png)

**Comment by 3arthur6** [comment]
Huh sorry about that.
Which phone? Which firmware version?

**Comment by 3arthur6** [comment]
> Samsung Galaxy A52s 5G A528BXXU1CVG8 But it doesn't matter, I just gave up and installed stock non rooted android because of too many issues and required workarounds.

Ok sorry, probably related to read only partition issue.
Multidisabler could have fixed it.

**Comment by arminask** [comment]
> 

Where can I find multidisabler? I am guessing it's a magisk modue that you flash?
