### ISSUE TITLE
Samsung Galaxy A11 Installation Failure - BluetoothLibPatcher-files.tar link

### ISSUE THREAD

**Issue by Skaldebane** [3arthur6/BluetoothLibraryPatcher#28]
Hi there! Trying to install this module through Fox's Magic Module Manager fails on my Galaxy A11 (Android 12), and guides me to this repo.

Here's the [BluetoothLibPatcher-files.tar](https://drive.google.com/file/d/1lX9Skbc8Pj3U-BlDVpR6350glvMs-R7s/view?usp=sharing) file.

I hope you can add support for this device. Thanks in advance!

**Comment by 3arthur6** [comment]
Hey!
Latest 2.5.1 version should fix it

**Comment by Skaldebane** [comment]
Thanks, it works now 👌🏻
