### ISSUE TITLE
Note10+ A12 Problems with Viper4Android_Repacked

### ISSUE THREAD

**Issue by filipenobrerc** [3arthur6/BluetoothLibraryPatcher#29]
After installing this module V4A stops processing.

**Comment by 3arthur6** [comment]
> After installing this module V4A stops processing.

Does it well fixed your bluetooth pairings issue?
If yes this problem is more in V4A side.
You could try to install this module first, reboot then install V4A.

**Comment by 3arthur6** [comment]
No response, so closing.
