### ISSUE TITLE
A52s Bluetooth broken

### ISSUE THREAD

**Issue by ThePutois** [3arthur6/BluetoothLibraryPatcher#31]
Hello, I installed this twrp zip hoping it would allow me to pair m'y galaxy watch 5 pro to m'y rooted a52s (stock rom), the flashing worked but bluetooth is now greyed out and unusable, I saw That the original file is backed up during patching, how to restore it please?

**Comment by 3arthur6** [comment]
Hey
Sorry for that. So on Android 13 right?
On A13 replace /system_root/system/lib64/libbluetooth_jni.so by /system_root/system/lib64/libbluetooth_jni.so.bak from twrp.
Otherwise in A12 do the same stuff but with libbluetooth.so

**Comment by ThePutois** [comment]
Hi, thanks for your reply, I did what you wrote but I still have the issue, do I need to refresh something more than restarting the device ? Thanks

**Comment by 3arthur6** [comment]
If you are on Android 13 totally remove the file.

**Comment by 3arthur6** [comment]
No response, so closing.
