### ISSUE TITLE
Samsung Galaxy A13 library not found

### ISSUE THREAD

**Issue by Exynos-nibba** [3arthur6/BluetoothLibraryPatcher#32]
**Device: Samsung Galaxy A13 
OS: Android 13 (OneUI 5 core)**

Module installation fails on _Android 13_ with a 

> library not found error

Device is **MTK based** so im guessing it has differently named or labeled libs? and no _lib64_ folder.
note: There is a _libbluetooth_mtk_ lib in the vendors folder

Magisk Installation log & a complete list of libs from the system and vendor folders is attached below and im guessing you would need a lot more than this, feel free to ask more logs, etc to debug the issue, thanks. 

[magisk_install_log_2023-01-02T20.07.50.log](https://github.com/3arthur6/BluetoothLibraryPatcher/files/10332630/magisk_install_log_2023-01-02T20.07.50.log)

[system-lib.txt](https://github.com/3arthur6/BluetoothLibraryPatcher/files/10332631/system-lib.txt)
[vendor-libs.txt](https://github.com/3arthur6/BluetoothLibraryPatcher/files/10332632/vendor-libs.txt)

**Comment by 3arthur6** [comment]
Most users don't need this module anymore on android 13, are you still losing bluetooth pairings?
Anyway I take a look on the Galaxy A13 firmware and the latest release (2.6.2) should handle it.

**Comment by Exynos-nibba** [comment]
> Most users don't need this module anymore on android 13, are you still losing bluetooth pairings? Anyway I take a look on the Galaxy A13 firmware and the latest release (2.6.2) should handle it.

Yep, the device still loses pairings even if i turn the bluetooth off and on after a few mins, 2.6.2 seems to have flashed successfully, will close the issue if the pairings stay after this, Thanks!

**Comment by Exynos-nibba** [comment]
Tested it, works perfectly fine.
