### ISSUE TITLE
Library Not Supported Samsung A70

### ISSUE THREAD

**Issue by SennaHammink** [3arthur6/BluetoothLibraryPatcher#34]
Hello,

I am just trying to install the module and get an error code that my phone is not supported and that I needed to make an issue comment.

My full model number of my phone is: sm-a705fn

Greetings,
Senna

**Comment by 3arthur6** [comment]
Hey!
Please provide the tar archive file created in the root internal storage of your phone after installing the module.
Without it there is nothing I can do.

**Comment by 3arthur6** [comment]
Closing as no responde.
