### ISSUE TITLE
A137F incompatible

### ISSUE THREAD

**Issue by dbn-21** [3arthur6/BluetoothLibraryPatcher#35]
Samsung A137F MTK

I get feedback saying the module is not compatible with the device.

I have uploaded the tar file here.
https://forum.xda-developers.com/t/bluetoothlibrarypatcher-fix-bluetooth-pairings-loss-android-13-12-11-10-pie-oreo-nougat.4017735/page-27?__cf_chl_tk=6Wjo3UlsvE5DjaJAtc5eTwciHLu0oTzqtPKdxwJEtBk-1680273079-0-gaNycGzNJOU

**Comment by 3arthur6** [comment]
Hey
It should be fixed with [v2.6.3](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.3)
Could you confirm?
Thanks

**Comment by dbn-21** [comment]
Hello
With the new update 2.6.3, I successfully installed my device with the A137F magisk method.

Now I can connect without pairing the bluetooth device each time, by turning on the bluetooth and selecting the device to connect to.
Thank you for this work and the new update.
