### ISSUE TITLE
Huawei band pair always lost even though module installed

### ISSUE THREAD

**Issue by Zeyad-dev** [3arthur6/BluetoothLibraryPatcher#36]
I have rooted my Samsung M52 5g, and I haven't been experiencing any Bluetooth pairs disconnection after restart, but recently it started happening with my Huawei band, that after restart, it can't restore any connection and I have to manually reconnect it from the Huawei health app.

Is there any solution to this issue?

Please inform me if you require any more information from my side.

**Comment by Zeyad-dev** [comment]
I forgot to mention my android version, I am on android 13

**Comment by 3arthur6** [comment]
Hi!
Sorry it only support galaxy watches and devices.
As I even don't own a galaxy watch I can afford support other brand.
