### ISSUE TITLE
Script Galaxy Watch devices support

### ISSUE THREAD

**Issue by ReMiOS** [3arthur6/BluetoothLibraryPatcher#39]
I am not sure if this is supposed to happen when i run these commands for the Galaxy Watch devices support
Since i haven't bought one yet i can't test it, but looking at the results it looks not as expected.

```
$ su
$ mount -o remount,rw /vendor
$ for i in `grep -lr 'security.wsm' /vendor/etc/vintf`; do [ ! -z $i ] && sed -i "$((`awk '/security.wsm/ {print FNR}' $i`-1)),/<\/hal>/d" $i; done
$ mount -o remount,ro /vendor
```

**Before running script:**
for i in `grep -lr 'security.wsm' /vendor/etc/vintf`; do echo $i;done
/vendor/etc/vintf/manifest.xml

grep  'vendor.samsung.hardware'  /vendor/etc/vintf/manifest.xml
        <name>vendor.samsung.hardware.audio</name>
        <name>vendor.samsung.hardware.biometrics.fingerprint</name>
        <name>vendor.samsung.hardware.bluetooth</name>
        <name>vendor.samsung.hardware.camera.provider</name>
        <name>vendor.samsung.hardware.gnss</name>
        <name>vendor.samsung.hardware.health</name>
        <name>vendor.samsung.hardware.light</name>
        <name>vendor.samsung.hardware.miscpower</name>
        <name>vendor.samsung.hardware.nfc</name>
        <name>vendor.samsung.hardware.radio</name>
        <name>vendor.samsung.hardware.radio.bridge</name>
        <name>vendor.samsung.hardware.radio.channel</name>
        <name>vendor.samsung.hardware.security.drk</name>
        <name>vendor.samsung.hardware.security.proca</name>
        <name>vendor.samsung.hardware.security.securestorage</name>
        <name>vendor.samsung.hardware.security.widevine.keyprovisioning</name>
        **<name>vendor.samsung.hardware.security.wsm</name>**
        <name>vendor.samsung.hardware.snap</name>
        <name>vendor.samsung.hardware.tlc.ucm</name>
        <name>vendor.samsung.hardware.vibrator</name>
        <name>vendor.samsung.hardware.wifi</name>
        <name>vendor.samsung.hardware.wifi.hostapd</name>
        <name>vendor.samsung.hardware.wifi.supplicant</name>

**After running the script it seems the line is removed**
grep 'vendor.samsung.hardware' /vendor/etc/vintf/manifest.xml
        <name>vendor.samsung.hardware.audio</name>
        <name>vendor.samsung.hardware.biometrics.fingerprint</name>
        <name>vendor.samsung.hardware.bluetooth</name>
        <name>vendor.samsung.hardware.camera.provider</name>
        <name>vendor.samsung.hardware.gnss</name>
        <name>vendor.samsung.hardware.health</name>
        <name>vendor.samsung.hardware.light</name>
        <name>vendor.samsung.hardware.miscpower</name>
        <name>vendor.samsung.hardware.nfc</name>
        <name>vendor.samsung.hardware.radio</name>
        <name>vendor.samsung.hardware.radio.bridge</name>
        <name>vendor.samsung.hardware.radio.channel</name>
        <name>vendor.samsung.hardware.security.drk</name>
        <name>vendor.samsung.hardware.security.proca</name>
        <name>vendor.samsung.hardware.security.securestorage</name>
        <name>vendor.samsung.hardware.security.widevine.keyprovisioning</name>
        <name>vendor.samsung.hardware.snap</name>
        <name>vendor.samsung.hardware.tlc.ucm</name>
        <name>vendor.samsung.hardware.vibrator</name>
        <name>vendor.samsung.hardware.wifi</name>
        <name>vendor.samsung.hardware.wifi.hostapd</name>
        <name>vendor.samsung.hardware.wifi.supplicant</name>

**Comment by 3arthur6** [comment]
Hi!
Yep it's exactly what it is supposed to do.
Removing this line nukes a services which can prevent pairing galaxy watches.

**Comment by ReMiOS** [comment]
Thanks 👌
