### ISSUE TITLE
Add short for Note 8 with Note 9 rom ported to it

### ISSUE THREAD

**Issue by j0p3s** [3arthur6/BluetoothLibraryPatcher#4]
I am running this rom so if you could add support for this it would be great!
Thanks in advance
Rom:https://forum.xda-developers.com/t/rom-10-hadesrom-q-v3-0-for-exynos-s8-s8-note8-04-02-2022.4208409/
Libpatcher backup: https://mega.nz/file/GYpAGDzD#kj25VbabCkxkfAFwRRZbfmG8p7N_g7K1W5HLlcTKW7c

**Comment by 3arthur6** [comment]
Hey
hadesRom is prepatched. You don't need any additional changes.
