### ISSUE TITLE
S23 A14

### ISSUE THREAD

**Issue by jrkruse** [3arthur6/BluetoothLibraryPatcher#42]
Patch not working on S23 Beta A14

**Comment by 3arthur6** [comment]
Hey
Could you confirm latest version [v2.6.4](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.4) addresses the issue?

**Comment by 3arthur6** [comment]
It seems ok according to other feedback.

**Comment by jrkruse** [comment]
Its fixed with your latest version
Thank you
