### ISSUE TITLE
Not working on Galaxy A54 5G

### ISSUE THREAD

**Issue by KAW0** [3arthur6/BluetoothLibraryPatcher#43]
Version 2.6.4
Android: 13
One UI: 5.1
Soft: A546BXXU5AWGJ

**Comment by 3arthur6** [comment]
Could you give more informations? Where is it failling?
Try to install it again. The library from A546BXXU5AWGJ software looks like any other.

**Comment by 3arthur6** [comment]
Closed as no answer since a month.
