### ISSUE TITLE
2.65 stalls at installation

### ISSUE THREAD

**Issue by ertmuirm** [3arthur6/BluetoothLibraryPatcher#46]
Have been using this module without issues for years. Just updated to 2.65 and module installation stalls at "applying gear watch fix" line. Worked fine with 2.64

S20, Stock A12, Magisk Delta

**Comment by 3arthur6** [comment]
I just updated the release.
Could you download it again from [here](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.5) and try again?

**Comment by ertmuirm** [comment]
> I just updated the release. Could you download it again from [here](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.5) and try again?

Works now. Thanks!

**Comment by ertmuirm** [comment]
Issue closed
