### ISSUE TITLE
Can't install Bluetoothlibrarypatcher 2.6.5

### ISSUE THREAD

**Issue by jsaa1973** [3arthur6/BluetoothLibraryPatcher#47]
I can't update/install

![Screenshot_20231003-125351](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/56712506/24a15dfb-d489-4f65-b557-1627a2ad28f2)

Can you help me please?

**Comment by 3arthur6** [comment]
Hey
As stated in the log, your system is already patched so the magisk module isn't needed.
I will change the log message to something more clear.

**Comment by jsaa1973** [comment]
I want to update from 2.6.4 to 2.6.5
