### ISSUE TITLE
dm-4 is readonly

### ISSUE THREAD

**Issue by green1052** [3arthur6/BluetoothLibraryPatcher#5]
i tried
```
$ su
$ mount -o remount,rw /vendor
$ for i in `grep -lr 'security.wsm' /vendor/etc/vintf`; do [ ! -z $i ] && sed -i "$((`awk '/security.wsm/ {print FNR}' $i`-1)),/<\/hal>/d" $i; done
$ mount -o remount,ro /vendor
```

but console said dm-4 is reload 

how to fix it?

my devices is S22+ and not installed twrp

thx!

**Comment by 3arthur6** [comment]
Hey,
You need twrp but it seems to still be at development stage.
Wait for it then flash the specific twrp zip.
It's not in my hand sorry.
