### ISSUE TITLE
Only for non aisp roms Although on oneui 5.1

### ISSUE THREAD

**Issue by elswerky** [3arthur6/BluetoothLibraryPatcher#50]
Hello
I used to flash this module on Note 10 lite
But I formatted device and flashed latest firmware October security patch 

And now when I flash it on Magick alpha it fails saying can't be use on asop rows 

Although am one oneuj v5.1 

Also tri3d to flash twep file but it stops at patching libraries

**Comment by fragtion** [comment]
Same problem on SM910F with latest Magisk Alpha. looking forward to a fix

**Comment by astrophilehuwan** [comment]
Same problem on Samsung A24, OneUI 6.0 and Magisk 26.4

**Comment by privacyguy123** [comment]
Same problem - my fault for opening a duplicate issue.

Perhaps you could take a look? :)

**Comment by Pharaoh2k** [comment]
@3arthur6 any news?

**Comment by 3arthur6** [comment]
Sorry for the delay
Latest [v2.6.6](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.6) release should fix this issue.

**Comment by shogunbr** [comment]
> Sorry for the delay Latest [v2.6.6](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.6) release should fix this issue.

The Kitsune Mask variant of Magisk (which replaces Magisk Delta) has the same problem on installation. Could you please also fix it for Kitsune?

**Comment by 3arthur6** [comment]
> The Kitsune Mask variant of Magisk (which replaces Magisk Delta) has the same problem on installation. Could you please also fix it for Kitsune?

Just done it.

**Comment by IcyColdified** [comment]
v2.6.8 now working on Galaxy A24 4G, OneUI 6.0, R65C33E4F-kitsune :+1:

**Comment by 3arthur6** [comment]
I assume this is now fixed this latest 2.7.0 release.
