### ISSUE TITLE
Can't install version 2.6.5 on OneUI 6

### ISSUE THREAD

**Issue by astrophilehuwan** [3arthur6/BluetoothLibraryPatcher#52]
I tried installing BluetoothLibraryPatcher on my Samsung A24 running on OneUi 6.0 Android 14 and it's saying installation failed.

**Comment by astrophilehuwan** [comment]
![magisk_install_log_2024-01-01T02.33.52.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/13801972/magisk_install_log_2024-01-01T02.33.52.zip)

**Comment by 3arthur6** [comment]
Latest [v2.6.6](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.6) release should fix your issue.

**Comment by 3arthur6** [comment]
I assume this is now fixed this latest 2.7.0 release.
