### ISSUE TITLE
Install script thinks device is not a Samsung

### ISSUE THREAD

**Issue by privacyguy123** [3arthur6/BluetoothLibraryPatcher#54]
![Screenshot_20240114_021248](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/50337995/14d47671-3c38-495e-8107-bc8c3e31d065)

Is it perhaps due to new commits pushed to Magisk Canary versions that change the file paths of su and mirror?

Device is Samsung S20 FE using latest Magisk Alpha Canary.

**Comment by 3arthur6** [comment]
I assume this is now fixed this latest 2.7.0 release.
