### ISSUE TITLE
Add support for Oneui6.0 (32bit) A135F

### ISSUE THREAD

**Issue by Aryanxfa** [3arthur6/BluetoothLibraryPatcher#56]
[BluetoothLibPatcher-files.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/14227836/BluetoothLibPatcher-files.zip)

Here is the files logs from A135F
(it will say A205F but the rom is different)
I tested the twrp variant with latest version v2.6.8

Thanks!

**Comment by 3arthur6** [comment]
[Latest release](https://github.com/3arthur6/BluetoothLibraryPatcher/releases/tag/v2.6.9) should fix it!

**Comment by Aryanxfa** [comment]
Thanks for adding support,
The updated version is working as expected.
You may close this issue
Thanks!
