### ISSUE TITLE
Samsung Galaxy A73

### ISSUE THREAD

**Issue by MrMasterDev** [3arthur6/BluetoothLibraryPatcher#57]
The module does not work on Galaxy A73 5G, Androidi 14, OneUI 6.0, Makisk Kitsune. Devices that are in the connected list,  do not reconnect to the phone after turning on-off bluetooth or after reboot phone.

**Comment by 3arthur6** [comment]
Did you enabled SuList?
Try to add `com.android.bluetooth` to it.
With this command `magiskhide add com.android.bluetooth`

**Comment by MrMasterDev** [comment]
> Did you enabled SuList? Try to add `com.android.bluetooth` to it. With this command `magiskhide add com.android.bluetooth`

This has been done for a long time, but it does not help. 
![Screenshot_20240215_155836](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/60237714/c2a30366-4ecb-4233-b8b0-ec763f099f89)
![Screenshot_20240215_155831](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/60237714/4e45561d-66dc-42c7-994f-c58435c11a9a)

**Comment by IcyColdified** [comment]
> Devices that are in the connected list do not reconnect to the phone after turning bluetooth on and off or rebooting the phone. 

Do you mean the devices are still on the "paired devices" list but not connecting to your device anymore? 
Or does the device completely disappear from the list after reboot?

**Comment by MrMasterDev** [comment]
> > Devices that are in the connected list do not reconnect to the phone after turning bluetooth on and off or rebooting the phone.
> 
> Do you mean the devices are still on the "paired devices" list but not connecting to your device anymore? Or does the device completely disappear from the list after reboot?

The devices are still on the "paired devices" list but not connecting to my device anymore?

**Comment by 3arthur6** [comment]
Ok so it seems to be another problem. Devices will totally disappear of the list without this patch.
Which kind of devices do you use?
Try to uninstall the module when reboot. Then install it again and reboot again.
In last resort you can try to reset network settings.

**Comment by MrMasterDev** [comment]
> > The devices are still on the "paired devices" list but not connecting to my device anymore.
> 
> Ok so it seems to be another problem. Devices will totally disappear of the list without this patch. Which kind of devices do you use? Try to uninstall the module when reboot. Then install it again and reboot again. In last resort you can try to reset network settings.

I have already done all this, several times and it did not help. Now I only use bluetooth headphones, sometimes I connect them to a TV or a speaker.

**Comment by 3arthur6** [comment]
Huh.. Maybe another module.
Have you tried disabling all other modules?

**Comment by MrMasterDev** [comment]
> Huh.. Maybe another module. Have you tried disabling all other modules?

What are the other modules for?

**Comment by 3arthur6** [comment]
Magisk modules.
Do you have any other ones?

**Comment by MrMasterDev** [comment]
> Magisk modules. Do you have any other ones?

There are other modules, but what do they have to do with your module?

**Comment by IcyColdified** [comment]
> There are other modules, but what do they have to do with your module?
> Isn't this a compatibility issue with magisk kitsune? 

It is indeed unlikely for other magisk modules to conflict with this module, but chances aren't zero xd

> I turned off all the modules, but it didn't help. But I found that everything works, but I constantly have to turn off and turn on the headphones. 

Does the exact same thing happen to the other devices you have mentioned?

**Comment by IcyColdified** [comment]
> > > There are other modules, but what do they have to do with your module?
> > > Isn't this a compatibility issue with magisk kitsune?
> > 
> > It is indeed unlikely for other magisk modules to conflict with this module, but chances aren't zero xd
> > 
> > > I turned off all the modules, but it didn't help. But I found that everything works, but I constantly have to turn off and turn on the headphones.
> > 
> > Does the exact same thing happen to the other devices you have mentioned?
> 
> So the same thing happens with other devices 

What have you done so far to investigate / resolve this issue? (Sorry)

**Comment by MrMasterDev** [comment]
> > > > There are other modules, but what do they have to do with your module?
> > > > Isn't this a compatibility issue with magisk kitsune?
> > > 
> > > 
> > > It is indeed unlikely for other magisk modules to conflict with this module, but chances aren't zero xd
> > > > I turned off all the modules, but it didn't help. But I found that everything works, but I constantly have to turn off and turn on the headphones.
> > > 
> > > 
> > > Does the exact same thing happen to the other devices you have mentioned?
> > 
> > 
> > So the same thing happens with other devices
> 
> What have you done so far to investigate / resolve this issue? (Sorry)
I did everything possible. I followed all your recommendations. I don't know what else can be done.

**Comment by MrMasterDev** [comment]
> > > > There are other modules, but what do they have to do with your module?
> > > > Isn't this a compatibility issue with magisk kitsune?
> > > 
> > > 
> > > It is indeed unlikely for other magisk modules to conflict with this module, but chances aren't zero xd
> > > > I turned off all the modules, but it didn't help. But I found that everything works, but I constantly have to turn off and turn on the headphones.
> > > 
> > > 
> > > Does the exact same thing happen to the other devices you have mentioned?
> > 
> > 
> > So the same thing happens with other devices
> 
> What have you done so far to investigate / resolve this issue? (Sorry)

After long tests, I found that in fact, it automatically connects to devices after restarting the phone, if the device to which you connect is turned off and then turned on, it is also automatically connected to it. Only if you turn off bluetooth on the phone and then turn it on, it will not automatically connect to the device to which it is connected.

**Comment by 3arthur6** [comment]
> After long tests, I found that in fact, it automatically connects to devices after restarting the phone, if the device to which you connect is turned off and then turned on, it is also automatically connected to it. Only if you turn off bluetooth on the phone and then turn it on, it will not automatically connect to the device to which it is connected.

So you don't loose your paired devices right?
This issue is related to auto connect?
The module doesn't change anything to this.

**Comment by MrMasterDev** [comment]
> > After long tests, I found that in fact, it automatically connects to devices after restarting the phone, if the device to which you connect is turned off and then turned on, it is also automatically connected to it. Only if you turn off bluetooth on the phone and then turn it on, it will not automatically connect to the device to which it is connected.
> 
> So you don't loose your paired devices right? This issue is related to auto connect? The module doesn't change anything to this.
 
Yes.I don't loose my paired devices. This issue is related to auto connect.

**Comment by 3arthur6** [comment]
> Yes.I don't loose my paired devices. This issue is related to auto connect.Is there any way to fix this? 

This module doesn't deal with auto connect sorry.
I don't have any information about this.
