### ISSUE TITLE
the module thinks that I don’t have a Samsung

### ISSUE THREAD

**Issue by HIB1tch123** [3arthur6/BluetoothLibraryPatcher#59]
![Screenshot_20240325_113949_MRepo](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/109823442/13848739-70d6-4698-8878-a91ae2b6f4e3)

Bluetooth was turned off at the time of installation

maybe one of these modules is interfering with the installation 
![Screenshot_20240325_114349](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/109823442/e4a8e2cc-b885-4f7d-9d99-00fa6c9b0893)
![Screenshot_20240325_114351](https://github.com/3arthur6/BluetoothLibraryPatcher/assets/109823442/1cc0f464-b600-45d4-ae61-fdfdc84b2baf)

**Comment by IcyColdified** [comment]
Are you using vanilla Magisk or others (Alpha, Kitsune/Delta, etc)?

Most modules shouldn't affect the installation of the module unless they heavily modify the build.prop, I believe.

**Comment by HIB1tch123** [comment]
I use regular magisk 27.0

**Comment by IcyColdified** [comment]
Have you tried disabling all the other modules, rebooting, and then installing the module?

**Comment by HIB1tch123** [comment]
this helped thanks, I really don’t understand why it didn't work before I also turned off all the modules and installed it on a completely clean system(
