### ISSUE TITLE
Bluetooth library issue

### ISSUE THREAD

**Issue by Armadauz** [3arthur6/BluetoothLibraryPatcher#6]
Hello Arthur, 
I have a favor for you. I tried install bluetooth library patcher to my Samsung Galaxy S10 5g . Originally SM-G977N but converted to SM-G977B by flashing with auto rooted and auto patched Android 12 by SOFT4GSM. Eaarlier was installed Bluetooth library patcher on this phone, Android 11. Magisk 23.0.  
At the moment installed Magisk 558710bb-alpha-2(23016) (installed together with above mentioned OS 12). I attached screenshot.  Also attaching log file. I can't install another version of Magisk. Because if I change something in magisk I got bootloop. 
Please help me to fix the bluetooth library patcher.  
Thank you in advance.
[magisk_install_log_2022-07-26T21_27_43.660.log](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9191704/magisk_install_log_2022-07-26T21_27_43.660.log)
![photo_2022-07-26_21-31-27](https://user-images.githubusercontent.com/84524528/181061359-0b93b1d4-a97e-4e48-b344-c84c743acd00.jpg)

**Comment by 3arthur6** [comment]
Hey
You should talk with your rom maintainer.
Your magisk version should be supported, I have no idea why the module couldn't be installed and there is nothing I can do.
