### ISSUE TITLE
None of the versions, from 2.6.4 to 2.6.9 (twrp as well as magisk) work on One UI 6.1

### ISSUE THREAD

**Issue by KaranChopra2806** [3arthur6/BluetoothLibraryPatcher#61]
I upgraded my phone (Galaxy S9+) to Noble Rom 4.1.1 running One UI 6.1, the devices keep disappearing after every restart even though the Patcher zip is always installed successfully in twrp and magisk.

Tried all the versions all the way from 2.6.4 to 2.6.9, none seem to have an effect, kindly help ( ´,_ゝ`)

**Comment by TwilightNougat** [comment]
same problem

**Comment by grasmanek94** [comment]
Same issue here

**Comment by 3arthur6** [comment]
I couldn't provide support for custom roms sorry. You should ask the rom developper for a fix.

**Comment by grasmanek94** [comment]
Oh for me it is happening on official samsung rom!

**Comment by 3arthur6** [comment]
Please open a new issue with more informations.
