### ISSUE TITLE
Hi can you support Apatch

### ISSUE THREAD

**Issue by egydoctor2010** [3arthur6/BluetoothLibraryPatcher#62]
This module is working good for me with magic
But when I try to install with apatch 
It gives a message that I am running also rom and not allowed.
Can you fix please

**Comment by 3arthur6** [comment]
Supported in latest release with https://github.com/3arthur6/BluetoothLibraryPatcher/commit/960bb0849a0b0b74717f4b9b5757e364303c8d50 commit.
