### ISSUE TITLE
Magisk module detects my Samsung Galaxy A9 2018 DS (A920F) as aosp or non Samsung firmware

### ISSUE THREAD

**Issue by blue-pine** [3arthur6/BluetoothLibraryPatcher#64]
Magisk module detects my Samsung Galaxy A9 2018 DS (A920F) as having aosp or non Samsung firmware. Please fix this as really felt the need to install this magisk module only to find this stupid error. Very problematic as losing bluetooth pairings. Help fast or tell me how to fix this myself if developer doesn't have time. 
I am using latest Magisk debug version 27004.
Also I feel the need to report one observation. I am having this issue after I factory reseted. Before factory reset I was using this version of this magisk module  [Bluetooth_Library_Patcher-v2.6.3(263).zip](https://github.com/user-attachments/files/16203496/Bluetooth_Library_Patcher-v2.6.3.263.zip)
. Earlier before factory reset this version and all versions before it were working but now after factory rest they too are giving same error as the latest version of this magisk module. Also I have not updated my firmware , it is as it was before factory reset. Only difference before and after factory rest could be a few things like Magisk debug version 27004 , some lsposed modules. After factory reset I also used multidisabler while before it I didn't use it and instead used disable encryption zip from zackptg5 flashed using twrp. Can't think of any other differences. But most probable is the new Magisk debug version why is my guess but could be wrong 

Also few times a while the modules passes Samsung check and gets stuck after printing something like ”..finding hex byte sequence. Applying patch". But never applies the patch.

But still after all this I expect you to fix this issue. Please fix this issue first as I gave a very detailed bug report apart from others. Feel free to ask me more
Thank you
Regards

Loved your software

**Comment by 3arthur6** [comment]
I assume this is now fixed this latest 2.7.0 release.
