### ISSUE TITLE
Patcher not executing

### ISSUE THREAD

**Issue by paratkd** [3arthur6/BluetoothLibraryPatcher#65]
I have a Galaxy S10 5G running stock Samsung firmware, albeit Magisk Kitsune patched for root.

Initially, the patch module refused to run as it was stating it is only for stock Samsung ROM; I skipped this by editing the customise.sh script.

However, now it gets to the "searching for hex byte pattern" stage and never moves any further. I let it run for a long time, no changes seem to be made. I also tried older version releases, but to no avail.

I'm currently stuck with my phone not pairing properly to my Wearable Watch6 (although buds seems to be fine.)

Many thanks 👍 

*EDIT*  I have tried to revert to a standard Magisk (latest) install, with no manager hidden, stable release channel etc, still no luck! 

Is there a way I can manually patch the file; I have access to pull any files off using root access, hex edit on PC and push back on. I don't have a custom recovery installed for flashing using TWRP for example, so can't use that file.

**Comment by usaingoldx** [comment]
Same device, same error. (I do close magisk app because is stuck same text. After i do reboot device , login magisk app and i see bluetooth library patcher module in the modules page. But not look working.)

**Comment by 3arthur6** [comment]
Could anyone confirm 2.7.0 fixed this too?
