### ISSUE TITLE
S24 Plus OneUi 6.1->6.1.1 update, bluetooth crashing

### ISSUE THREAD

**Issue by KrazyDeinos** [3arthur6/BluetoothLibraryPatcher#67]
Updated to OneUi 6.1.1 and after update Bluetooth is crashing.
Tested to disable reboot enable the module, no effect. 

A re-install failed with the error message like other users have reported:
"only for samsung stock roms not relevant for aosp roms!"

Tested disabling the modules Tricky Store and Play Integrity Fork, no effect.

6.1.1 was a big update for OneUi, so this module may need some tweaking for it to work.

**Comment by KrazyDeinos** [comment]
Log

`- Copying zip to temp directory
- Installing BluetoothLibraryPatcher_module_2.6.9.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***************************
 Bluetooth Library Patcher 
 by 3arthur6 
***************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: 7z.tar.xz
  inflating: 7z64.tar.xz
  inflating: README.md
  inflating: SUPPORT.md
  inflating: bash.tar.xz
  inflating: bash64.tar.xz
  inflating: busybox.tar.xz
  inflating: customize.sh
  inflating: hexpatch.sh
  inflating: latestchange.log
  inflating: module.prop
  inflating: service.sh
  inflating: update.json
- Magisk Manager installation
grep: /debug_ramdisk/.magisk/mirror/system/build.prop: No such file or directory
- Only for Samsung stock based roms!
- Not relevant for aosp roms!

! Installation failed
`

**Comment by KrazyDeinos** [comment]
According to this commit, from magisk 27005 an onwards, magisk isnt using mirror:
https://github.com/topjohnwu/Magisk/commit/92b305a389bcb0dc7e2b3169134f0a81bac6c513

Can I edit service.sh to this? :
`check() {
  samsung=`grep -Eqw "androidboot.odin_download|androidboot.warranty_bit|sec_debug" /proc/cmdline && echo 'true' || echo 'false'`
  if [[ ! -z $KSU_VER ]] ; then
    ui_print "- KernelSU Manager installation"
    sys=/system
  elif $BOOTMODE ; then
    ui_print "- Magisk Manager installation"
    if [[ $MAGISK_VER == *-alpha ]] || [[ $MAGISK_VER == *-kitsune ]]; then
      ui_print "- Magisk Alpha/Kitsune fork detected"
      sys=/system
    else
      # Use the system path directly since the mirror is no longer available
      sys=/system
    fi
  else`

**Comment by 3arthur6** [comment]
Thanks for pointing out this I will push an update right now.

**Comment by KrazyDeinos** [comment]
> Thanks for pointing out this I will push an update right now.

@3arthur6  I tested 2.7.0 now , sadly 

`- Copying zip to temp directory
- Installing BluetoothLibraryPatcher_module_2.7.0.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***************************
 Bluetooth Library Patcher 
 by 3arthur6 
***************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: 7z.tar.xz
  inflating: 7z64.tar.xz
  inflating: README.md
  inflating: SUPPORT.md
  inflating: bash.tar.xz
  inflating: bash64.tar.xz
  inflating: busybox.tar.xz
  inflating: customize.sh
  inflating: hexpatch.sh
  inflating: latestchange.log
  inflating: module.prop
  inflating: service.sh
  inflating: update.json
sh: 0495468d: bad number
- Magisk Manager installation
grep: /debug_ramdisk/.magisk/mirror/system/build.prop: No such file or directory
- Only for Samsung stock based roms!
- Not relevant for aosp roms!

! Installation failed
`
Perhaps the 6.1.1 changed quite a bit from 6.1

**Comment by 3arthur6** [comment]
Thanks, I pushed the update a bit to quick..
It should be ok.

**Comment by KrazyDeinos** [comment]
> Thanks, I pushed the update a bit to quick.. It should be ok.

Thanks @3arthur6 , now it goes further, although stuck at "searching for relevant hex byte sequence" , and later "applying patch"
I saw this in the last release, with and older magisk, to see if the module would work with the 6.1.1 update. 
I had it be stuck there for about  30min before i rebooted, and after  a reboot with magisk module install still stuck, the module would be active but not working, and bluetooth crashing as an result.

But maybe it will be different this time and "applying patch" finishes.

**Comment by 3arthur6** [comment]
ok!
Could you please attach here the file /system/apex/com.android.btservices.apex from you phone?
You will need a root file manager.

**Comment by KrazyDeinos** [comment]
> ok! Could you please attach here the file /system/apex/com.android.btservices.apex from you phone? You will need a root file manager.

Here you of @3arthur6 , it's zipped because of GitHub attachment limitations 
[Uploading com.android.btservices.zip…]()

**Comment by 3arthur6** [comment]
I think you sent the message before the file was fully uploaded I can't download it

**Comment by KrazyDeinos** [comment]
[com.android.btservices.zip](https://github.com/user-attachments/files/17180983/com.android.btservices.zip)
@3arthur6  sorry buddy =)

**Comment by 3arthur6** [comment]
Thanks dude! It will need more investigation on my part

**Comment by KrazyDeinos** [comment]
Sure thing! Happy to help, and good hunting!
You've been awesome pushing this module out for users to experience bluetooth to work as it should work =)

**Comment by KrazyDeinos** [comment]
@3arthur6 the install actually finished, after roughly an hour, and the module is working, did a few reboot tests and connection tests. All good!
Maybe this will be somewhat helpful 😀

**Comment by KrazyDeinos** [comment]
> @KrazyDeinos Could you try with one? [BluetoothLibraryPatcher_module_2.7.0.zip](https://github.com/user-attachments/files/17248729/BluetoothLibraryPatcher_module_2.7.0.zip) I should fix performance regression and so installation time.

@3arthur6 you are a magician! Tested now, instant install, bt devices still remembered, Bluetooth connects and running fine ! 🍺😀

**Comment by 3arthur6** [comment]
Thanks dude!
I will release it soon

**Comment by 3arthur6** [comment]
I assume this is now fixed. Feel free to open again if any issue occurs.
