### ISSUE TITLE
Samsung Galaxy A80 Android 11 not supported

### ISSUE THREAD

**Issue by TheSingular** [3arthur6/BluetoothLibraryPatcher#7]
Title explains it well I believe. I have repacked the .tar into .zip and uploaded it here, link is below.

I'd be happy if you could help me with that. Thanks in advance.

[BluetoothLibPatcher-files.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9277702/BluetoothLibPatcher-files.zip)

**Comment by 3arthur6** [comment]
Hey
I didn't found why it fails.
Could you try again with the latest release and post the new tar file?

**Comment by TheSingular** [comment]
> Hey I didn't found why it fails. Could you try again with the latest release and post the new tar file?

**Comment by TheSingular** [comment]
> > Hey I didn't found why it fails. Could you try again with the latest release and post the new tar file?

Sure, did it just now and it failed again. 
![Screenshot_20220810-012121](https://user-images.githubusercontent.com/18699171/183772403-5d4a173f-b09e-4633-87f5-0282f42d8cfe.jpg)

New tar below.
[BluetoothLibPatcher-files.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9294964/BluetoothLibPatcher-files.zip)

Also accidentally closed the issue just now, reopened it so please ignore that.

**Comment by TheSingular** [comment]
Hey I just tried to install the v2.3.1 version from the old repo and it worked somehow. I don't know why. At least I won't lose my pairings again.

**Comment by 3arthur6** [comment]
Could you give it one last try?

**Comment by TheSingular** [comment]
Yeah the lastest one worked.
