### ISSUE TITLE
Installation failed on my Samsung Galaxy Note 9 

### ISSUE THREAD

**Issue by ZeroDev99** [3arthur6/BluetoothLibraryPatcher#8]
Failed installation strip and the signal bar went away 
![Screenshot_20220809-152219](https://user-images.githubusercontent.com/98488108/183764038-81f76ab1-3349-4ad8-8231-0998fff319aa.png)

**Comment by 3arthur6** [comment]
Sorry it have been fixed. Install it again.

**Comment by ZeroDev99** [comment]
That's fine thanks
