### ISSUE TITLE
My library is no longer supported since 2.4.2 update

### ISSUE THREAD

**Issue by tharubberchicken** [3arthur6/BluetoothLibraryPatcher#9]
Samsung Galaxy S10e running Android 10 One UI 2.5.
[BluetoothLibPatcher-files.zip](https://github.com/3arthur6/BluetoothLibraryPatcher/files/9294977/BluetoothLibPatcher-files.zip)

**Comment by 3arthur6** [comment]
Sorry it have been fixed. Install it again.

**Comment by tharubberchicken** [comment]
Thanks, works great again! 👍🏻
